apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: vault
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-status: "update"
    vault.hashicorp.com/agent-inject-secret-login: "kv2/data/nginx"
    vault.hashicorp.com/agent-inject-template-login: |
          {{- with secret "kv2/data/nginx" -}}
          password={{ .Data.data.password }}
          {{- end }}
    vault.hashicorp.com/role: "vault-role"
    vault.hashicorp.com/agent-inject-file-login: "application.properties"
    vault.hashicorp.com/secret-volume-path-login: "/app"
spec:
  serviceAccountName: vault-serviceaccount
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
