apiVersion: v1
kind: Pod
metadata:
  name: java-pod
  namespace: vault
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-status: "update"
    vault.hashicorp.com/agent-inject-secret-login: "kv2/data/hoge"
    vault.hashicorp.com/agent-inject-template-login: |
          {{- with secret "kv2/data/hoge" -}}
          password={{ .Data.data.password }}
          {{- end }}
    vault.hashicorp.com/role: "hoge-role"
    vault.hashicorp.com/agent-inject-file-login: "application.properties"
    vault.hashicorp.com/secret-volume-path-login: "/root/deployment"
spec:
  serviceAccountName: vault-serviceaccount
  containers:
  - name: java-app
    image: daisukezr/vault-demo-java:latest
    ports:
      - containerPort: 8080
